In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# step1. Import libraries

In [2]:
import tensorflow as tf
import keras
from keras.datasets import mnist

from keras.models import Sequential
from keras.layers import Dense,Flatten

# step2.Read the dataset

In [3]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [4]:
num_classes=10

# step3. ANN model(development)

In [5]:
model=Sequential()
model.add(Flatten(input_shape=(28,28)))
model.add(Dense(128,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(num_classes,activation='softmax'))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 10)                650       
                                                                 
Total params: 109,386
Trainable params: 109,386
Non-trainable params: 0
_________________________________________________________________


# 4.compile and train the model

In [7]:
model.compile(loss="sparse_categorical_crossentropy",optimizer=keras.optimizers.Adadelta(),metrics=['accuracy'])

In [8]:
batch_size=128
epochs=20

model.fit(x_train,y_train,batch_size=batch_size,epochs=epochs,verbose=1,validation_data=(x_test,y_test))

Epoch 1/20
469/469 [==============================] - 2s 4ms/step - loss: 134.6967 - accuracy: 0.1057 - val_loss: 104.9664 - val_accuracy: 0.1151
Epoch 2/20
469/469 [==============================] - 2s 4ms/step - loss: 84.5612 - accuracy: 0.1399 - val_loss: 66.7430 - val_accuracy: 0.1658
Epoch 3/20
469/469 [==============================] - 2s 4ms/step - loss: 56.0109 - accuracy: 0.1993 - val_loss: 45.3221 - val_accuracy: 0.2448
Epoch 4/20
469/469 [==============================] - 2s 4ms/step - loss: 39.5905 - accuracy: 0.2709 - val_loss: 33.2541 - val_accuracy: 0.3153
Epoch 5/20
469/469 [==============================] - 2s 4ms/step - loss: 30.4000 - accuracy: 0.3389 - val_loss: 26.5235 - val_accuracy: 0.3801
Epoch 6/20
469/469 [==============================] - 2s 4ms/step - loss: 25.0221 - accuracy: 0.3938 - val_loss: 22.3621 - val_accuracy: 0.4316
Epoch 7/20
469/469 [==============================] - 2s 4ms/step - loss: 21.5060 - accuracy: 0.4416 - val_loss: 19.4589 - val_accurac

# Evaluate the model

In [9]:
loss,acc=model.evaluate(x_test,y_test)
print("Test Accuracy",acc)

313/313 [==============================] - 1s 2ms/step - loss: 7.7677 - accuracy: 0.7027
Test Accuracy 0.7027000188827515


In [10]:
predictions=model.predict(x_test)
predictions

313/313 [==============================] - 1s 1ms/step


array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 9.9999994e-01,
        0.0000000e+00, 0.0000000e+00],
       [1.0460171e-09, 5.7474789e-09, 9.9999994e-01, ..., 0.0000000e+00,
        3.2718048e-13, 0.0000000e+00],
       [3.3607289e-25, 9.8592125e-02, 5.7990003e-19, ..., 3.8735239e-12,
        7.6024342e-18, 1.0556301e-25],
       ...,
       [0.0000000e+00, 0.0000000e+00, 3.5173121e-34, ..., 2.3932884e-19,
        9.9987906e-01, 1.2057370e-04],
       [3.5568953e-37, 1.7360521e-31, 2.8366769e-17, ..., 2.8155318e-20,
        5.7785527e-08, 1.2893653e-33],
       [0.0000000e+00, 0.0000000e+00, 3.5597494e-25, ..., 0.0000000e+00,
        3.5240582e-37, 0.0000000e+00]], dtype=float32)

In [11]:
import numpy as np
predict_prob=model.predict(x_test)
predict_classes=np.argmax(predict_prob,axis=1)
print(predict_classes)
print(y_test)

313/313 [==============================] - 0s 1ms/step
[7 2 3 ... 8 5 6]
[7 2 1 ... 4 5 6]


In [12]:
model=Sequential()
model.add(Flatten(input_shape=(28,28)))
model.add(Dense(128,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(num_classes,activation='softmax'))


In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_3 (Dense)             (None, 128)               100480    
                                                                 
 dense_4 (Dense)             (None, 128)               16512     
                                                                 
 dense_5 (Dense)             (None, 10)                1290      
                                                                 
Total params: 118,282
Trainable params: 118,282
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(loss="sparse_categorical_crossentropy",optimizer=keras.optimizers.Adagrad(),metrics=['accuracy'])

In [15]:
batch_size=128
epochs=30

model.fit(x_train,y_train,batch_size=batch_size,epochs=epochs,verbose=1,validation_data=(x_test,y_test))

Epoch 1/30
469/469 [==============================] - 2s 4ms/step - loss: 6.7580 - accuracy: 0.7645 - val_loss: 3.3371 - val_accuracy: 0.8490
Epoch 2/30
469/469 [==============================] - 2s 3ms/step - loss: 2.9111 - accuracy: 0.8592 - val_loss: 2.5674 - val_accuracy: 0.8726
Epoch 3/30
469/469 [==============================] - 2s 3ms/step - loss: 2.2954 - accuracy: 0.8788 - val_loss: 2.1920 - val_accuracy: 0.8859
Epoch 4/30
469/469 [==============================] - 2s 4ms/step - loss: 1.9483 - accuracy: 0.8904 - val_loss: 1.9706 - val_accuracy: 0.8932
Epoch 5/30
469/469 [==============================] - 2s 4ms/step - loss: 1.7107 - accuracy: 0.8985 - val_loss: 1.8175 - val_accuracy: 0.8983
Epoch 6/30
469/469 [==============================] - 2s 4ms/step - loss: 1.5333 - accuracy: 0.9047 - val_loss: 1.7229 - val_accuracy: 0.8992
Epoch 7/30
469/469 [==============================] - 2s 4ms/step - loss: 1.3992 - accuracy: 0.9096 - val_loss: 1.6277 - val_accuracy: 0.9041
Epoch 

In [16]:
loss,acc=model.evaluate(x_test,y_test)
print("Test Accuracy",acc)

313/313 [==============================] - 0s 2ms/step - loss: 1.0739 - accuracy: 0.9238
Test Accuracy 0.923799991607666


In [17]:
model=Sequential()
model.add(Flatten(input_shape=(28,28)))
model.add(Dense(128,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(num_classes,activation='softmax'))


In [18]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_6 (Dense)             (None, 128)               100480    
                                                                 
 dense_7 (Dense)             (None, 128)               16512     
                                                                 
 dense_8 (Dense)             (None, 10)                1290      
                                                                 
Total params: 118,282
Trainable params: 118,282
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.compile(loss="sparse_categorical_crossentropy",optimizer=keras.optimizers.Adagrad(),metrics=['accuracy'])

In [20]:
batch_size=128
epochs=10

model.fit(x_train,y_train,batch_size=batch_size,epochs=epochs,verbose=1,validation_data=(x_test,y_test))

Epoch 1/10
469/469 [==============================] - 2s 4ms/step - loss: 5.9298 - accuracy: 0.7759 - val_loss: 3.0261 - val_accuracy: 0.8437
Epoch 2/10
469/469 [==============================] - 2s 4ms/step - loss: 2.4740 - accuracy: 0.8645 - val_loss: 2.2673 - val_accuracy: 0.8687
Epoch 3/10
469/469 [==============================] - 2s 4ms/step - loss: 1.9137 - accuracy: 0.8847 - val_loss: 1.9263 - val_accuracy: 0.8796
Epoch 4/10
469/469 [==============================] - 2s 4ms/step - loss: 1.6108 - accuracy: 0.8946 - val_loss: 1.7384 - val_accuracy: 0.8885
Epoch 5/10
469/469 [==============================] - 2s 4ms/step - loss: 1.4101 - accuracy: 0.9041 - val_loss: 1.6084 - val_accuracy: 0.8937
Epoch 6/10
469/469 [==============================] - 2s 4ms/step - loss: 1.2641 - accuracy: 0.9100 - val_loss: 1.5022 - val_accuracy: 0.8967
Epoch 7/10
469/469 [==============================] - 2s 4ms/step - loss: 1.1544 - accuracy: 0.9150 - val_loss: 1.4365 - val_accuracy: 0.9005
Epoch 

In [21]:
loss,acc=model.evaluate(x_test,y_test)
print("Test Accuracy",acc)

313/313 [==============================] - 1s 2ms/step - loss: 1.2848 - accuracy: 0.9069
Test Accuracy 0.9068999886512756
